RNN
1. What is a Sequence?
English
A sequence is data where order matters.

For example:

10 → 20 → 30 → 40 → 50
These numbers might represent:

Day 1 → Day 2 → Day 3 → Day 4 → Day 5

In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.tensor([
    [1.0],
    [2.0],
    [3.0],
    [4.0],

])

In [3]:
print(x)
print(x.shape)

tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])


5 time steps
1 feature

In [6]:

lstm = nn.LSTM(
    input_size=1,
    hidden_size=16,
    num_layers=1,
    batch_first=True
)

In [7]:
x = torch.tensor([
    [
        [1.0],
        [2.0],
        [3.0],
        [4.0],
        [5.0]
    ]
])

print(x.shape)

torch.Size([1, 5, 1])


1 = batch size
5 = sequence length
1 = number of features

In [10]:
output, (hidden, cell) = lstm(x)

In [13]:

print("Output:")
print(output)

print("Hidden:")
print(hidden)

print("Cell:")
print(cell)

Output:
tensor([[[-0.0667, -0.0008, -0.0021, -0.0336, -0.0679, -0.0123, -0.0199,
           0.1210, -0.0557,  0.0218,  0.0113, -0.0525,  0.1001, -0.0122,
           0.0567, -0.0499],
         [-0.1153, -0.0243,  0.0145, -0.0751, -0.1413, -0.0255,  0.0181,
           0.2026, -0.1075,  0.0603,  0.0321, -0.0929,  0.1296, -0.0437,
           0.1608, -0.0691],
         [-0.1547, -0.0432,  0.0314, -0.1143, -0.2179, -0.0437,  0.0545,
           0.2574, -0.1521,  0.1126,  0.0572, -0.1193,  0.1181, -0.0926,
           0.2858, -0.0661],
         [-0.1882, -0.0502,  0.0432, -0.1447, -0.2922, -0.0632,  0.0722,
           0.2929, -0.1926,  0.1709,  0.0804, -0.1342,  0.0880, -0.1570,
           0.4033, -0.0453],
         [-0.2157, -0.0479,  0.0494, -0.1641, -0.3596, -0.0802,  0.0733,
           0.3142, -0.2332,  0.2271,  0.0986, -0.1404,  0.0542, -0.2331,
           0.5014, -0.0093]]], grad_fn=<TransposeBackward0>)
Hidden:
tensor([[[-0.2157, -0.0479,  0.0494, -0.1641, -0.3596, -0.0802,  0.0733,
    

In [14]:
import torch
import torch.nn as nn


# Create a simple sequence
x = torch.tensor([
    [
        [1.0],
        [2.0],
        [3.0],
        [4.0],
        [5.0]
    ]
])


# Create LSTM
lstm = nn.LSTM(
    input_size=1,
    hidden_size=16,
    num_layers=1,
    batch_first=True
)


# Pass sequence through LSTM
output, (hidden, cell) = lstm(x)


# Print shapes
print("Input shape:", x.shape)
print("Output shape:", output.shape)
print("Hidden shape:", hidden.shape)
print("Cell shape:", cell.shape)

Input shape: torch.Size([1, 5, 1])
Output shape: torch.Size([1, 5, 16])
Hidden shape: torch.Size([1, 1, 16])
Cell shape: torch.Size([1, 1, 16])


1. What is a sequence?
2. What is an RNN?
3. What is hidden state?
4. What is vanishing gradient?
5. Why do we use LSTM?