Linear Regression
🇬🇧 Simple idea

Linear Regression tries to find a line that best fits the data.
Predict a numerical value.

|   Size | Price |
| -----: | ----: |
|  50 m² | $100k |
|  70 m² | $140k |
|  90 m² | $180k |
| 110 m² | $220k |


we want the computer to learn if i give the size of the house can you predict it 
regression predict anumrical value


Price
  |
220|             *
200|          *
180|       *
160|    *
140|  *
120|
100|*
  +-------------------- Size
    50  70  90 110

x = input
y = prediction
w = weight / slope
b = bias / intercept

In [1]:
X = [50, 70, 90, 110]

y = [100, 140, 180, 220]

A cost function tells us:

How wrong is our model?

اگر prediction خیلی با مقدار واقعی فرق داشته باشد:

Cost = HIGH
اگر prediction نزدیک مقدار واقعی باشد:

Cost = LOW
هدف:

Minimize the cost.

 Mean Squared Error — MSE
یکی از cost functionهای مهم برای Linear Regression:

MSE

یعنی:

Mean Squared Error

فرمول:

MSE = 1/n Σ(y - ŷ)²
Don't worry about memorizing it today.

Gradient
    ↓
Direction
    ↓
Update parameters
    ↓
Cost decreases

 ### What is a Gradient?
Gradient به ما می‌گوید:

Which direction should we move to reduce the cost?

1️⃣2️⃣ Learning Rate
Gradient Descent یک مفهوم بسیار مهم دیگر دارد:

learning_rate
Learning rate مشخص می‌کند:

How big a step should we take?

مثلاً:

learning_rate = 0.01
یعنی قدم‌های کوچک.

اگر خیلی بزرگ باشد:

learning_rate = 10
ممکن است از minimum رد شویم.

Iteration 1 → Cost = 1000
Iteration 2 → Cost = 700
Iteration 3 → Cost = 450
Iteration 4 → Cost = 200
Iteration 5 → Cost = 80

Data
 ↓
Initialize w and b
 ↓
Make predictions
 ↓
Calculate Cost
 ↓
Calculate Gradient
 ↓
Update w and b
 ↓
Calculate Cost again
 ↓
Repeat

In [2]:
import numpy as np
X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

w = 0
b = 0
prediction = w * X + b
print(prediction)

[0 0 0 0 0]


In [6]:
import numpy as np
X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

w = 2
b = 0
prediction = w * X + b
print(prediction)

[ 2  4  6  8 10]


In [12]:
import numpy as np
X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

w = 2
b = 0
predictions = w * X + b
error = y - predictions
mse = np.mean(error ** 2)
print("Predictions:", predictions)
print("MSE:", mse)

print(prediction)

Predictions: [ 2  4  6  8 10]
MSE: 0.0
[ 2  4  6  8 10]


. Regression
برای پیش‌بینی عدد استفاده می‌شود.

House size → House price
2. Linear Regression:

یک خط برای پیدا کردن رابطه بین داده‌ها می‌سازد.

y = wx + b
3. X:

ورودی / Features

X = house size
4. y:

مقدار واقعی که می‌خواهیم پیش‌بینی کنیم.Prediction
مدل با w و b مقدار پیش‌بینی می‌کند.

6. Cost Function
می‌گوید مدل چقدر اشتباه کرده.

7. MSE
یکی از روش‌های محاسبه Cost در Linear Regression است.

8. Gradient Descent
روشی برای پیدا کردن w و b بهتر است.

9. Learning Rate
اندازه قدم‌های Gradient Descent را مشخص می‌کند