Input Text
    ↓
Tokenization
    ↓
Embeddings
    ↓
Positional Encoding
    ↓
Self-Attention
    ↓
Feed Forward Network
    ↓
Output

In [ ]:
Input
  ↓
Multi-Head Attention
  ↓
Add & Norm
  ↓
Feed Forward Network
  ↓
Add & Norm
  ↓
Output

| BERT                                  | GPT                                        |
| ------------------------------------- | ------------------------------------------ |
| Encoder                               | Decoder                                    |
| بیشتر برای understanding              | بیشتر برای generation                      |
| متن را برای درک context پردازش می‌کند | متن را به‌صورت autoregressive تولید می‌کند |
| مثال: classification                  | مثال: text generation                      |


In [1]:
import numpy as np
scores = np.array([1.0, 2.0, 3.0])
attention_weights = np.exp(scores) / np.exp(scores).sum()

In [2]:
print(attention_weights)

[0.09003057 0.24472847 0.66524096]


In [3]:
print(attention_weights.sum())

1.0


In [4]:
import numpy as np

tokens = ["I", "love", "Python"]

positions = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

print("Tokens:")
print(tokens)

print("\nPositional information:")
print(positions)

Tokens:
['I', 'love', 'Python']

Positional information:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
