In [44]:
import numpy as np
from sklearn.preprocessing import StandardScaler

X = np.array([
    [20, 20000],
    [25, 30000],
    [30, 50000],
    [40, 100000]
])

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X) # type: ignore

print(X_scaled)

[[-1.18321596 -0.97332853]
 [-0.50709255 -0.64888568]
 [ 0.16903085  0.        ]
 [ 1.52127766  1.62221421]]


In [45]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split  # type: ignore

X = np.array([
    [20, 20000],
    [25, 30000],
    [30, 50000],
    [40, 100000]
])

X_train, X_test = train_test_split(
    X,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[-1.18321596 -0.97332853]
 [-0.50709255 -0.64888568]
 [ 0.16903085  0.        ]
 [ 1.52127766  1.62221421]]


In [46]:
X_train_sacled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [47]:
from sklearn.model_selection import train_test_split  # type: ignore
from sklearn.preprocessing import StandardScaler
import numpy as np
X = np.array([
    [18, 15000],
    [22, 25000],
    [30, 40000],
    [35, 60000],
    [45, 120000]
])

scaler = StandardScaler()
X_train, X_test = train_test_split(
    X,
    test_size=0.2,
    random_state=42

)
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_train)
print(X)
print(X_scaled)

[[    18  15000]
 [    22  25000]
 [    30  40000]
 [    35  60000]
 [    45 120000]]
[[-1.18321596 -0.97332853]
 [-0.50709255 -0.64888568]
 [ 0.16903085  0.        ]
 [ 1.52127766  1.62221421]]


In [48]:
print(X_scaled.mean(axis=0))

[0. 0.]


In [49]:
print(X_scaled.std(axis=0))

[1. 1.]


 Feature چیست؟
English
Suppose we want to predict house prices.

Our dataset might look like:

| Size | Bedrooms | Age |  Price |
| ---: | -------: | --: | -----: |
|  100 |        2 |  10 | 300000 |
|  150 |        3 |   5 | 450000 |
|  200 |        4 |   2 | 600000 |


X = features
y = target

In [50]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import numpy as np

In [51]:
X = np.array([
    [100, 2],
    [150, 3],
    [200, 4],
    [250, 5],
    [300, 6],
    [350, 7]
])

y = np.array([
    200000,
    300000,
    400000,
    500000,
    600000,
    700000
])

In [52]:
X_train, X_test, y_train, y_test = train_test_split( # type: ignore
    X,
    y,
    test_size=0.2,
    random_state=42
)
scaler = StandardScaler()

In [53]:
X_train_scaled = scaler.fit_transform(X_test)
X_test_scaled = scaler.transform(X_test)

In [54]:
print("orignal:")
print(X_train)
print("Scaled:")
print(X_train_scaled)

orignal:
[[350   7]
 [200   4]
 [300   6]
 [250   5]]
Scaled:
[[-1. -1.]
 [ 1.  1.]]


In [68]:

from sklearn.pipeline import Pipeline
from sklearn .linear_model import LinearRegression

X = np.array([
    [20, 3000],
    [25, 4000],
    [30, 5000],
    [35, 6000],
    [40, 7000],
    [45, 8000],
    [50, 9000],
    [55, 10000]
])

y = np.array([
    100,
    120,
    150,
    180,
    200,
    230,
    250,
    280
])
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
model = Pipeline([
    ("scaler", StandardScaler()),
    ("regression", LinearRegression())
])
model.fit(X_train, y_train)
predictions = model.predict([[50, 9000]])
print(predictions)

[252.6]


fit():
Model learns from training data.

predict():Use the learned model to make predictions.

X_train
   │
   ▼
StandardScaler
   │
   ▼
Scaled X_train
   │
   ▼
LinearRegression
   │
   ▼
Trained Model

In [69]:
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


X = np.array([
    [100, 2],
    [150, 3],
    [200, 4],
    [250, 5],
    [300, 6],
    [350, 7],
    [400, 8],
    [450, 9]
])

y = np.array([
    200000,
    300000,
    400000,
    500000,
    600000,
    700000,
    800000,
    900000
])


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)


model = Pipeline([
    ("scaler", StandardScaler()),
    ("regressor", LinearRegression())
])


model.fit(X_train, y_train)


predictions = model.predict(X_test)


mse = mean_squared_error(y_test, predictions)

print("Predictions:", predictions)
print("Actual:", y_test)
print("MSE:", mse)

Predictions: [300000. 700000.]
Actual: [300000 700000]
MSE: 8.470329472543003e-21
